process.env.NODE_ENV = 'test'
process.env.PORT = '3333'
process.env.CORS_ORIGIN = 'http://localhost:3000'
process.env.DB_PATH = ':memory:'
process.env.JWT_SECRET = 'test-jwt-secret-not-for-production'
process.env.JWT_EXPIRES_IN = '15m'
process.env.REFRESH_EXPIRES_IN = '7d'
